from tkinter import *
def click1():
    etiqueta['text'] = "Olá " + entrada.get()
janela = Tk()
janela.title("Empresa")
janela.iconbitmap('icone.ico')
janela['bg']=('pink')
janela.geometry('500x400+50+200')
entrada=Entry(janela, width=80,)
entrada.pack()
entrada.get()
etiqueta=Label(janela,text = "Olá Magna", bg=('pink'), cursor="dot")
etiqueta.pack()
botao=Button(janela, bg=('light blue'),text="Click", padx='80', pady='20', command=click1)
botao.pack()
janela.mainloop()